FROM node:16-alpine

RUN mkdir /app
WORKDIR /app  

# Copy package.json and package-lock.json to the container 

# Copy the app source code to the container  
COPY ./ ./

RUN npm install

RUN npm run build
# Expose the port the app will run on  
EXPOSE 3000  

# Start the app  
CMD ["npm", "start"]