version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend/src:/usr/app/src
    ports:
      - '3000:3000'
    tty: true # comunicate with terminal
    stdin_open: true # open in/out connection from the terminal
    environment:
      - REACT_APP_PORT=3001
    networks:
      - entrancegranted
    container_name: entrancegranted-frontend

  backend:
    build:
      context: ./backend
    command: npm run dev
    volumes:
      - ./backend/src:/usr/app/src
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    networks:
      - entrancegranted
    container_name: entrancegranted-backend


  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    # restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs:/data
    ports:
      - 2049:2049
    networks:
      - entrancegranted
    container_name: entrancegranted-nfs

  mongodb:
    volumes:
      - ./mongo_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
    networks:
      - entrancegranted
    container_name: entrancegranted-mongodb

# volumes:
#    mongo_db:

networks:
  entrancegranted:
    driver: bridge
